# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sub', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_statement', models.CharField(max_length=2000)),
                ('inp', models.CharField(max_length=2000)),
                ('out', models.CharField(max_length=2000)),
                ('constra', models.CharField(max_length=2000)),
                ('eg', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=2000)),
            ],
        ),
    ]
