# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prob_code',
            field=models.CharField(default='Unknown', max_length=40),
            preserve_default=False,
        ),
    ]
