# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0002_question_prob_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub',
            field=models.IntegerField(default=0, verbose_name=b'Successful Submission'),
        ),
        migrations.AlterField(
            model_name='queslist',
            name='sub',
            field=models.IntegerField(default=0, verbose_name=b'Successful Submission'),
        ),
        migrations.AlterField(
            model_name='question',
            name='constra',
            field=models.CharField(max_length=2000, verbose_name=b'Constraints'),
        ),
        migrations.AlterField(
            model_name='question',
            name='eg',
            field=models.CharField(max_length=2000, verbose_name=b'Example'),
        ),
        migrations.AlterField(
            model_name='question',
            name='inp',
            field=models.CharField(max_length=2000, verbose_name=b'Input'),
        ),
        migrations.AlterField(
            model_name='question',
            name='out',
            field=models.CharField(max_length=2000, verbose_name=b'Output'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prob_code',
            field=models.CharField(max_length=40, verbose_name=b'Problem Code'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prob_statement',
            field=models.CharField(max_length=2000, verbose_name=b'Problem Statement'),
        ),
    ]
